" Use plain vim
" when vim was invoked by 'sudo' command
" or, invoked as 'git difftool'
if exists('$SUDO_USER') || exists('$GIT_DIR')
  finish
endif

" =====================
" Options
" =====================

" Set file encoding as UTF-8
set encoding=utf-8
" Enable true color
set termguicolors
" Enable syntax highlighting (automatically disabled when tree-sitter is enabled)
syntax enable

" Confirm on quit
set confirm

" Don't create backup
set nobackup
set nowritebackup
" Disable swap file
set noswapfile

" Always show the signcolumn, otherwise it would shift the text each time
" diagnostics appeared/became resolved
set signcolumn=yes

" Show relative column number
set number
set relativenumber

" Highlight column number
set cursorline

" Visualize invisible string
set list
set listchars=eol:$,tab:>-,trail:·,extends:>,precedes:<

" Indentation
set smarttab
set autoindent
set softtabstop=0

" Always display statusline.
set laststatus=2

" Yank texts to system clipboard
if has('unnamedplus')
  set clipboard=unnamedplus
else
  set clipboard=unnamed
endif

" Set <Leader> as the space key
let mapleader = " "

" Load ctags if exists
set tags=./tags;

" Automatic word wrapping
set colorcolumn=75
set textwidth=75
filetype indent plugin on

" Enable spell check
set spelllang=en_us

autocmd FileType text setlocal spell
autocmd FileType markdown setlocal spell
autocmd FileType gitcommit setlocal spell

autocmd FileType text setlocal complete+=kspell
autocmd FileType markdown setlocal complete+=kspell
autocmd FileType gitcommit setlocal complete+=kspell

" Return to last edit position when opening files
augroup ReturnToLastPosition
  autocmd!
  autocmd BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$") | exe "normal! g`\"" | endif
augroup END

" Save files when focus lost
augroup AutoSaveOnFocusLost
  autocmd!
  autocmd FocusLost * silent! wa
augroup END

" Change background color when focus lost
augroup FocusBackground
  autocmd!
  autocmd FocusLost * hi Normal guibg=#1A1C29
  autocmd FocusGained * hi Normal guibg=#0F111A
augroup END

" =====================
" Syntax
" =====================

" Recognize .def files as C++
augroup CppFiletype
  autocmd!
  autocmd BufNewFile,BufRead *.def		set filetype=cpp
augroup END

" Set JFlex syntax
augroup filetype
  au BufRead,BufNewFile *.flex,*.jflex		set filetype=jflex
augroup END
au Syntax jflex so ~/.vim/syntax/jflex.vim

" Mojo
" Mojo files use either .mojo or .🔥 as extension
au BufNewFile,BufRead *.mojo,*.🔥		setf mojo
au Syntax mojo so ~/.vim/syntax/mojo.vim

" Cup
au BufNewFile,BufRead *.cup			setf cup
au Syntax cup so ~/.vim/syntax/cup.vim

" =====================
" Key Mappings
" =====================

"
" Normal Mode
"

" Treat ; as :
nnoremap ; :

" Visually move cursor
nnoremap j gj
nnoremap k gk

" Move to the beginning of line
nnoremap <S-h> ^
" Move to the beginning of file
nnoremap <S-k> gg
" Move to the end of line
nnoremap <S-l> $
" Move to the end of file
nnoremap <S-j> G

" Buffer navigation
nnoremap <silent> <Leader>w :bdelete<Cr>

"
" Insert Mode
"

" Escape with jj & kk
inoremap jj <Esc>
inoremap kk <Esc>

"
" Visual Mode
"

" Indent
vnoremap <Tab> >gv
vnoremap <S-Tab> <gv
