[[ssh-keys]]
item = "GitHub"

[[ssh-keys]]
item = "CSE 484"
vault = "Education"

[[ssh-keys]]
item = "UW Attu"
vault = "Education"

[[ssh-keys]]
item = "UW GitLab"
vault = "Education"

[[ssh-keys]]
item = "ThinkPad"

[[ssh-keys]]
item = "GCC"

[[ssh-keys]]
item = "Git Signing"
