[[ssh-keys]]
item = "Git Signing"

[[ssh-keys]]
item = "GitHub"

[[ssh-keys]]
item = "UW GitLab"
vault = "Education"

[[ssh-keys]]
item = "UW Attu"
vault = "Education"

[[ssh-keys]]
item = "ThinkPad"

[[ssh-keys]]
item = "GCC"
