---
# defaults write domain key -type value
# defaults write -g key -type value
- name: Ask to keep changes when closing documents
  osx_defaults:
    key: NSCloseAlwaysConfirmsChanges
    type: bool
    value: true

- name: Require password immediately after sleep or screen saver begins
  osx_defaults:
    domain: com.apple.screensaver
    key: askForPasswordDelay
    type: int
    value: 0

- name: Screen Saver never starts
  osx_defaults:
    domain: com.apple.screensaver
    key: idleTime
    type: int
    value: 0

- name: Dock size
  osx_defaults:
    domain: com.apple.dock
    key: tilesize
    type: float
    value: 47
- name: Turn on Dock Magnification
  osx_defaults:
    domain: com.apple.dock
    key: magnification
    type: bool
    value: true
- name: Dock Magnification
  osx_defaults:
    domain: com.apple.dock
    key: largesize
    type: float
    value: 113
- name: Automatically hide and show the Dock
  osx_defaults:
    domain: com.apple.dock
    key: autohide
    type: bool
    value: true

- name: Minimize windows into application icon
  osx_defaults:
    domain: com.apple.dock
    key: minimize-to-application
    type: bool
    value: true

- name: Launchpad icon size
  osx_defaults:
    domain: com.apple.dock
    key: springboard-columns
    type: int
    value: 10
- name: Launchpad icon size
  osx_defaults:
    domain: com.apple.dock
    key: springboard-rows
    type: int
    value: 8
- name: Launchpad icon size
  osx_defaults:
    domain: com.apple.dock
    key: ResetLaunchPad
    type: bool
    value: true

- name: Show Hard disks on the desktop
  osx_defaults:
    domain: com.apple.finder
    key: ShowHardDrivesOnDesktop
    type: int
    value: 1

- name: New Finder windows show...
  osx_defaults:
    domain: com.apple.finder
    key: NewWindowTarget
    type: string
    value: PfDo
- name: New Finder windows show...
  osx_defaults:
    domain: com.apple.finder
    key: NewWindowTargetPath
    type: string
    value: "file://~/Documents/"

- name: Do not show Recents on the sidebar
  osx_defaults:
    domain: com.apple.finder
    key: ShowRecentTags
    type: int
    value: 0

- name: Speed up dialog display and window resize speed
  osx_defaults:
    key: NSWindowResizeTime
    value: 0.1

- name: Fastest Key Repeat
  osx_defaults:
    key: KeyRepeat
    type: int
    value: 2
- name: Shortest Delay Until Repeat
  osx_defaults:
    key: InitialKeyRepeat
    type: int
    value: 15

- name: ¥ key generates \ (backslash)
  osx_defaults:
    domain: com.apple.inputmethod.Kotoeri
    key: JIMPrefCharacterForYenKey
    type: int
    value: 1

- name: Show the battery percentage in the menu bar
  osx_defaults:
    domain: com.apple.menuextra.battery
    key: ShowPercent
    type: string
    value: "YES"

- name: Configure screenshot (1)
  osx_defaults:
    domain: com.apple.screencapture
    key: name
    value: ScreenShot
- name: Configure screenshot (2)
  osx_defaults:
    domain: com.apple.screencapture
    key: include-date
    type: bool
    value: false
- name: Configure screenshot (3)
  osx_defaults:
    domain: com.apple.screencapture
    key: location
    value: ~/Downloads
- name: Do not display thumbnail
  osx_defaults:
    domain: com.apple.screencapture
    key: show-thumbnail
    type: bool
    value: false

- name: Fastest Trackpad speed
  osx_defaults:
    domain: com.apple.trackpad
    key: scaling
    type: float
    value: 3

- name: Show volume on the menu bar (1)
  osx_defaults:
    domain: com.apple.menuextra
    key: volume
    type: bool
    value: true
- name: Show volume in menu bar (2)
  shell: defaults write com.apple.systemuiserver.plist menuExtras -array-add "/System/Library/CoreServices/Menu Extras/Volume.menu"

- name: Show bluetooth on the menu bar (1)
  osx_defaults:
    domain: com.apple.menuextra
    key: bluetooth
    type: bool
    value: true
- name: Show bluetooth on the menu bar (2)
  shell: defaults write com.apple.systemuiserver.plist menuExtras -array-add "/System/Library/CoreServices/Menu Extras/Bluetooth.menu"

# https://www.defaults-write.com/display-the-file-extensions-in-finder/
- name: Show all filename extensions on Finder
  osx_defaults:
    key: AppleShowAllExtensions
    type: bool
    value: true

#
# Siri
#
- name: Disable Ask Siri
  osx_defaults:
    domain: com.apple.assistant.support.plist
    key: "Assistant Enabled"
    type: bool
    value: false
- name: Hide Siri in menu bar
  osx_defaults:
    domain: com.apple.Siri
    key: StatusMenuVisible
    type: bool
    value: false

#
# Security Privacy
#
- name: Ask for password
  shell: defaults write com.apple.screensaver askForPassword -bool true
- name: Ask for password immediately
  shell: defaults write com.apple.screensaver askForPasswordDelay -int 0

#
# Desktop
#
- name: Increase grid spacing for icons on the desktop and in other icon views
  shell: /usr/libexec/PlistBuddy -c 'Set :DesktopViewSettings:IconViewSettings:gridSpacing 85' ~/Library/Preferences/com.apple.finder.plist
- name: Show item info near icons on the desktop and in other icon views
  shell: /usr/libexec/PlistBuddy -c 'Set :DesktopViewSettings:IconViewSettings:showItemInfo true' ~/Library/Preferences/com.apple.finder.plist
- name: text size on the desktop
  shell: /usr/libexec/PlistBuddy -c 'Set :DesktopViewSettings:IconViewSettings:textSize 10' ~/Library/Preferences/com.apple.finder.plist
