---
# defaults write domain key -type value
# defaults write -g key -type value
- name: Ask to keep changes when closing documents
  osx_defaults:
    key: NSCloseAlwaysConfirmsChanges
    type: bool
    value: true
- name: Require password immediately after sleep or screen saver begins
  osx_defaults:
    domain: com.apple.screensaver
    key: askForPasswordDelay
    type: int
    value: 0

- name: Dock size
  osx_defaults:
    domain: com.apple.dock
    key: tilesize
    type: float
    value: 47
- name: Turn on Dock Magnification
  osx_defaults:
    domain: com.apple.dock
    key: magnification
    type: bool
    value: true
- name: Dock Magnification
  osx_defaults:
    domain: com.apple.dock
    key: largesize
    type: float
    value: 113

- name: Minimize windows into application icon
  osx_defaults:
    domain: com.apple.dock
    key: minimize-to-application
    type: bool
    value: true
- name: Launchpad icon size
  osx_defaults:
    domain: com.apple.dock
    key: springboard-columns
    type: int
    value: 10
- name: Launchpad icon size
  osx_defaults:
    domain: com.apple.dock
    key: springboard-rows
    type: int
    value: 8
- name: Launchpad icon size
  osx_defaults:
    domain: com.apple.dock
    key: ResetLaunchPad
    type: bool
    value: true
- name: Show Hard disks on the desktop
  osx_defaults:
    domain: com.apple.finder
    key: ShowHardDrivesOnDesktop
    type: int
    value: 1
- name: New Finder windows show...
  osx_defaults:
    domain: com.apple.finder
    key: NewWindowTarget
    type: string
    value: PfDo
- name: New Finder windows show...
  osx_defaults:
    domain: com.apple.finder
    key: NewWindowTargetPath
    type: string
    value: "file://~/Documents/"
- name: Do not show Recents in the sidebar
  osx_defaults:
    domain: com.apple.finder
    key: ShowRecentTags
    type: int
    value: 0
- name: Speed up dialog display and window resize speed
  osx_defaults:
    key: NSWindowResizeTime
    value: 0.1
- name: Fastest Key Repeat
  osx_defaults:
    key: KeyRepeat
    type: int
    value: 2
- name: Shortest Delay Until Repeat
  osx_defaults:
    key: InitialKeyRepeat
    type: int
    value: 15

- name: Turn off Live Conversion
  osx_defaults:
    domain: com.apple.inputmethod.Kotoeri
    key: JIMPrefLiveConversionKey
    type: int
    value: 0

- name: ¥ key generates \ (backslash)
  osx_defaults:
    domain: com.apple.inputmethod.Kotoeri
    key: JIMPrefCharacterForYenKey
    type: int
    value: 1

- name: Show the battery percentage in the menu bar
  osx_defaults:
    domain: com.apple.menuextra.battery
    key: ShowPercent
    type: string
    value: "YES"

- name: Configure screenshot (1)
  osx_defaults:
    domain: com.apple.screencapture
    key: name
    value: ScreenShot
- name: Configure screenshot (2)
  osx_defaults:
    domain: com.apple.screencapture
    key: include-date
    type: bool
    value: false
- name: Configure screenshot (3)
  osx_defaults:
    domain: com.apple.screencapture
    key: location
    value: ~/Downloads

- name: Fastest Trackpad speed
  osx_defaults:
    domain: com.apple.trackpad
    key: scaling
    value: 3

- name: Show volume in menu bar (1)
  osx_defaults:
    domain: com.apple.menuextra
    key: volume
    type: bool
    value: true
- name: Show volume in menu bar (2)
  shell: defaults write com.apple.systemuiserver.plist menuExtras -array-add "/System/Library/CoreServices/Menu Extras/Volume.menu"

- name: Show bluetooth in menu bar (1)
  osx_defaults:
    domain: com.apple.menuextra
    key: bluetooth
    type: bool
    value: true
- name: Show bluetooth in menu bar (2)
  shell: defaults write com.apple.systemuiserver.plist menuExtras -array-add "/System/Library/CoreServices/Menu Extras/Bluetooth.menu"

- name: Show time machine in menu bar (1)
  osx_defaults:
    domain: com.apple.menuextra
    key: TimeMachine
    type: bool
    value: true
- name: Show time machine in menu bar (2)
  shell: defaults write com.apple.systemuiserver.plist menuExtras -array-add "/System/Library/CoreServices/Menu Extras/TimeMachine.menu"

- name: Change the computer name
  osx_defaults:
    domain: com.apple.rapport
    key: familySyncedName
    type: string
    value: "matken-mbp2018"

# https://www.defaults-write.com/display-the-file-extensions-in-finder/
- name: Show all filename extensions on Finder
  osx_defaults:
    key: AppleShowAllExtensions
    type: bool
    value: true
- name: Increase grid spacing for icons on the desktop and in other icon views
  shell: /usr/libexec/PlistBuddy -c 'Set :DesktopViewSettings:IconViewSettings:gridSpacing 85' ~/Library/Preferences/com.apple.finder.plist
- name: Show item info near icons on the desktop and in other icon views
  shell: /usr/libexec/PlistBuddy -c 'Set :DesktopViewSettings:IconViewSettings:showItemInfo true' ~/Library/Preferences/com.apple.finder.plist
- name: text size on the desktop
  shell: /usr/libexec/PlistBuddy -c 'Set :DesktopViewSettings:IconViewSettings:textSize 10' ~/Library/Preferences/com.apple.finder.plist
#- name: Move focus to next window by 'option + tab' on Keyboard Shortcuts
#  shell: /usr/libexec/PlistBuddy -c 'Set :AppleSymbolicHotKeys:27:value:parameters:0 65535' ~/Library/Preferences/com.apple.symbolichotkeys.plist
#- name: same process
#  shell: /usr/libexec/PlistBuddy -c 'Set :AppleSymbolicHotKeys:27:value:parameters:1 48' ~/Library/Preferences/com.apple.symbolichotkeys.plist
#- name: same process
#  shell: /usr/libexec/PlistBuddy -c 'Set :AppleSymbolicHotKeys:27:value:parameters:2 524288' ~/Library/Preferences/com.apple.symbolichotkeys.plist
