---
anyenv:
  - name: exenv
    version: "$(exenv install -l | grep -v : | grep -v - | grep -v / | head -1)"
  - name: goenv
    version: "$(goenv install -l | tail -1)"
  - name: ndenv
    version: "$(ndenv install -l | grep -v - | tail -1)"
  - name: pyenc
    version: "$(pyenv install -l | grep -v - | grep -v b | grep 3.6.* | tail -1)"
  - name: rbenv
    version: "$(rbenv install -l | grep -v - | tail -1)"

