---
homebrew_taps:
  - kryptco/tap # for kr
  - homebrew/cask-fonts # for font-hack-nerd-font
homebrew_packages:
  - name: asciinema
#  - name: awscli
  - name: boost
#  - name: boost-python
#  - name: circleci
  - name: clang-format
  - name: cmake
  - name: coreutils
  - name: curl
#  - name: elixir
  - name: elm
  - name: exa
#  - name: erlang
#  - name: font-hack-nerd-font
  - name: gh  # github cli
#  - name: ghc
  - name: go
  - name: graphviz
  - name: gzip
#  - name: httrack
  - name: hyperfine
  - name: interactive-rebase-tool
  - name: jq
  - name: kitty
#  - name: kops
  - name: kr
#  - name: kubectl
#  - name: llvm # clangd
#  - name: lsd
  - name: mas
  - name: neovim
  - name: peco
  - name: python
  - name: starship
  - name: terminal-notifier
#  - name: terraform
  - name: topgrade
  - name: tree
#  - name: valgrind
  - name: wget
  - name: wrk
#  - name: yaml-cpp
#  - name: youtube-dl
  - name: zoom
  - name: zplug
homebrew_cask_packages:
  - name: affinity-designer
#  - name: atom
  - name: balenaetcher
  - name: deepl
  - name: discord
  - name: docker
  - name: drawio
  - name: dropbox
  - name: figma
#  - name: firefox
  - name: font-source-code-pro-for-powerline
#  - name: framer-x
#  - name: fritzing
  - name: google-chrome
  - name: google-cloud-sdk
  - name: google-japanese-ime
  - name: grammarly
#  - name: hyper
  - name: imobie-m1-app-checker
  - name: jetbrains-toolbox
#  - name: keybase
#  - name: keysmith
#  - name: lens
  - name: macs-fan-control
#  - name: mendeley
#  - name: miro
#  - name: mysqlworkbench
  - name: notion
  - name: numi
  - name: parallels
#  - name: processing
  - name: postman
  - name: protonvpn
#  - name: sketch
  - name: swish
#  - name: tor-browser
  - name: visual-studio-code
#   - name: qfinder-pro  
