---
homebrew_taps:
  - kryptco/tap # for kr
homebrew_packages:
  - name: python@2
  - name: python
  - name: go
  - name: coreutils
  - name: kubectl
  - name: kops
  - name: ghc
  - name: boost
  - name: boost-python
  - name: mas
  - name: awscli
  - name: terraform
  - name: neovim
  - name: terminal-notifier
  - name: cmake
  - name: tree
  - name: kr
  - name: elm
  - name: yaml-cpp
  - name: zsh-syntax-highlighting
  - name: clang-format
  - name: llvm # clangd
  - name: graphviz  # keras.plot_model
homebrew_cask_packages:
  - name: google-chrome
  - name: iterm2
  - name: firefox
  - name: docker
#  - name: virtualbox
#  - name: vagrant
    #  - name: adobe-creative-cloud
  - name: jetbrains-toolbox
  - name: visual-studio-code
  - name: atom
  - name: google-cloud-sdk
    #  - name: etcher
  - name: qfinder-pro
  - name: dropbox
  - name: sketch
  - name: mendeley-desktop

