---
- name: update
  homebrew:
    update_homebrew: yes
- name: tap
  homebrew_tap:
    name: '{{ item }}'
    state: present
  with_items: '{{ homebrew_taps }}'
- name: install packages
  homebrew:
    name: '{{ item.name }}'
    state: '{{ item.state | default("present") }}'
    install_options: '{{ item.Install | default() | join(",") }}'
  with_items: '{{ homebrew_packages }}'
- name: install cask packages
  homebrew_cask: name={{ item.name }} state=installed
  environment:
    HOMEBREW_CASK_OPTS: "--appdir=/Applications"
  with_items: '{{ homebrew_cask_packages }}'
