---
tasks:
  - name: homebrew update
    homebrew:
      update_homebrew: yes
  - name: homebrew tap
    homebrew_tap:
      name: '{{ item }}'
      state: present
    with_items: '{{ homebrew_taps }}'
  - name: homebrew packages install
    homebrew:
      name: '{{ item.name }}'
      state: '{{ item.state | default("present") }}'
      install_options: '{{ item.Install | default() | join(",") }}'
    with_items: '{{ homebrew_packages }}'
  - name: homebrew cask packages install
    homebrew_cask: name={{ item.name }} state=installed
    environment:
      HOMEBREW_CASK_OPTS: "--appdir=/Applications"
    with_items: '{{ homebrew_cask_packages }}'
