[homebrew]
taps = [
    { name = "homebrew/cask-fonts", on = "macos" },  # for font-jetbrains-mono-nerd-font
]
formulae = [
    "atuin",
    # "asciinema",
    # "awscli",
    "bat",
    "black",
    "boost",
    "clang-format",
    "cmake",
    "curl",
    "difftastic",
    "fd",  # for telescope.nvim
    "ffmpeg",  # for youtube-dl
    "gh",
    "git-delta",
    "git-interactive-rebase-tool",
    "google-java-format",
    "graphviz",
    "gzip",
    "htop",
    # "httrack",
    "hyperfine",
    "jq",
    "ripgrep",
    "libarchive",
    "libgit2",
    "llvm",  # clangd, clang-format, clang-tidy
    "lsd",
    # "mysql",  # for mysqlclient of Python
    "ninja",
    "neomutt",
    "neovim",
    "node",
    "poetry",
    "python",
    "starship",
    "subversion",  # for font-source-code-pro-for-powerline
    "tmux",
    "topgrade",
    { name = "trash", on = "macos" },
    "universal-ctags",
    # "valgrind",
    "w3m",
    "wget",
    "wrk",
    "youtube-dl",
]
casks = [
    "1password",
    "1password-cli",
    "alacritty",
    # "balenaetcher",  # Flash OS images to SD cards & USB drives, safely and easily.
    "bartender",
    "cursor",
    "deepl",
    "discord",
    "docker",
    # "figma",
    "firefox",
    "font-jetbrains-mono-nerd-font",  # for alacritty
    "font-source-code-pro-for-powerline",
    "google-chrome",
    # "google-cloud-sdk",
    "grammarly-desktop",
    # "jetbrains-toolbox",
    "mactex-no-gui",
    # "mendeley",
    "notesnook",
    "postman",
    "raycast",
    # "sf-symbols",
    "signal",
    # "sketch",
    "swish",
    "zoom",
    # "zulip",
]

[cargo]
crates = [
    "cargo-update",
    "cargo-cache",
    "suggest-command-not-found",
]
