- hosts: localhost
  connection: local
  handlers:
    - name: Restart Dock
      shell: "killall Dock"
    - name: Restart Finder
      shell: "killall Finder"
# defaults write domain key -type value
# defaults write -g key -type value
  tasks:
    - name: Darken the menu bar and the dock
      osx_defaults:
        key: AppleInterfaceStyle
        type: string
        value: Dark
    - name: 書類を閉じるときに変更内容を保持するかどうかを確認
      osx_defaults:
        key: NSCloseAlwaysConfirmsChanges
        type: bool
        value: true
    - name: "スリープとスクリーンセーバの解除にパスワードを要求 開始後: すぐに"
      osx_defaults:
        domain: com.apple.screensaver
        key: askForPasswordDelay
        type: int
        value: 0
    - name: "ファイアウォール: 入"
      osx_defaults:
        domain: /Library/Preferences/com.apple.alf
        key: globalstate
        type: int
        value: 1
    - name: Dock size
      osx_defaults:
        domain: com.apple.dock
        key: tilesize
        type: int
        value: 40
    - name: Dock 拡大
      osx_defaults:
        domain: com.apple.dock
        key: magnification
        type: bool
        value: true
    - name: Dock 拡大量
      osx_defaults:
        domain: com.apple.dock
        key: largesize
        type: int
        value: 113
    - name: ウインドウをアプリケーションアイコンにしまう
      osx_defaults:
        domain: com.apple.dock
        key: minimize-to-application
        type: bool
        value: true
    - name: Launchpad icon size
      osx_defaults:
        domain: com.apple.dock
        key: springboard-columns
        type: int
        value: 9
    - name: Launchpad icon size
      osx_defaults:
        domain: com.apple.dock
        key: springboard-rows
        type: int
        value: 7
    - name: Launchpad icon size
      osx_defaults:
        domain: com.apple.dock
        key: ResetLaunchPad
        type: bool
        value: TRUE
    - name: ハードディスクをデスクトップに表示
      osx_defaults:
        domain: com.apple.finder
        key: ShowHardDrivesOnDesktop
        type: int
        value: 1
    - name: 新規Finderウィンドウで次を表示
      osx_defaults:
        domain: com.apple.finder
        key: NewWindowTarget
        type: string
        value: PfDo
    - name: 新規Finderウィンドウで次を表示
      osx_defaults:
        domain: com.apple.finder
        key: NewWindowTargetPath
        type: string
        value: "file://~/Documents/"
    - name: サイドバーの最近使ったタグを非表示
      osx_defaults:
        domain: com.apple.finder
        key: ShowRecentTags
        type: int
        value: 0
    - name: クイックルックで文字列を選択できるように
      osx_defaults:
        domain: com.apple.finder
        key: QLEnableTextSelection
        type: bool
        value: true
    - name: ダイアログ表示やウィンドウリサイズ速度を高速化
      osx_defaults:
        key: NSWindowResizeTime
        value: 0.1
    - name: "キーのリピート: 最大"
      osx_defaults:
        key: KeyRepeat
        type: int
        value: 2
    - name: "リピート入力認識までの時間: 最大"
      osx_defaults:
        key: InitialKeyRepeat
        type: int
        value: 15
    - name: ライブ変換オフ
      osx_defaults:
        domain: com.apple.inputmethod.Kotoeri
        key: JIMPrefLiveConversionKey
        type: int
        value: 0
    - name: "句読点の種類: ．と，"
      osx_defaults:
        domain: com.apple.inputmethod.Kotoeri
        key: JIMPrefPunctuationTypeKey
        type: int
        value: 3
    - name: "'￥'キーで入力する文字 -> \ backslash"
      osx_defaults:
        domain: com.apple.inputmethod.Kotoeri
        key: JIMPrefCharacterForYenKey
        type: int
        value: 1
    - name: Show the battery percentage from the menu bar
      osx_defaults:
        domain: com.apple.menuextra.battery
        key: ShowPercent
        type: string
        value: YES
    - name: Screen shot
      osx_defaults:
        domain: com.apple.screencapture
        key: name
        value: ScreenShot
    - name: Screen shot
      osx_defaults:
        domain: com.apple.screencapture
        key: include-date
        type: bool
        value: false
    - name: Screen shot
      osx_defaults:
        domain: com.apple.screencapture
        key: location
        value: ~/Downloads
    - name: "軌跡の速さ: 最速"
      osx_defaults:
        domain: com.apple.trackpad.scaling
        value: 3
    # https://www.defaults-write.com/display-the-file-extensions-in-finder/
    - name: "Finder: 全てのファイル名拡張子を表示"
      osx_defaults:
        key: AppleShowAllExtensions
        type: bool
        value: true
    - name: Increase grid spacing for icons on the desktop and in other icon views
      shell: /usr/libexec/PlistBuddy -c 'Set :DesktopViewSettings:IconViewSettings:gridSpacing 85' ~/Library/Preferences/com.apple.finder.plist
    - name: Show item info near icons on the desktop and in other icon views
      shell: /usr/libexec/PlistBuddy -c 'Set :DesktopViewSettings:IconViewSettings:showItemInfo true' ~/Library/Preferences/com.apple.finder.plist
    - name: "キーボードショートカット: 次のウィンドウを操作対象にする． => option + tab"
      shell: /usr/libexec/PlistBuddy -c 'Set :AppleSymbolicHotKeys:27:value:parameters:0 65535' ~/Library/Preferences/com.apple.symbolichotkeys.plist
    - name: same process
      shell: /usr/libexec/PlistBuddy -c 'Set :AppleSymbolicHotKeys:27:value:parameters:1 48' ~/Library/Preferences/com.apple.symbolichotkeys.plist
    - name: same process
      shell: /usr/libexec/PlistBuddy -c 'Set :AppleSymbolicHotKeys:27:value:parameters:2 524288' ~/Library/Preferences/com.apple.symbolichotkeys.plist
